### PR TITLE
Using no existing property for default User scheme

### PR DESCRIPTION
**Pull request by sokolnikov911**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | -

### CODE REVIEW

**Comment by cebe** [comment]
can you explain why you made this change?

**Comment by sokolnikov911** [comment]
cebe, because on described [here](https://github.com/yiisoft/yii2-authclient/blob/master/docs/guide/installation.md) db-scheme no "github" parameter. This can be misleading.

**Comment by cebe** [comment]
it is used later in `updateUserInfo()` so it seems to be needed for the code to work.
I think a note should be added to point out the change in schema instead of removing it.

**Comment by sokolnikov911** [comment]
yes, i think it's shold be removed from `updateUserInfo()` too

**Comment by cebe** [comment]
why? it is an example that shows how to update external attributes

**Comment by sokolnikov911** [comment]
so, maybe need to add some comment in code, for describe it?

**Comment by klimov-paul** [comment]
PR is incorrect since `github` field used later at `updateUserInfo()` method anyway.

**Pull request closed without merging**
