### PR TITLE
Fix assets path

### PR DESCRIPTION
**Pull request by Anton-Am**
Update assets path for new version of yii2.

### CODE REVIEW

**Comment by samdark** [comment]
Why's that? Path wasn't changed.

**Comment by Anton-Am** [comment]
I get problem with wrong asset paths after composer install. Can u check it pls?

**Comment by samdark** [comment]
Do you have https://github.com/yiisoft/yii2-app-basic/blob/master/composer.json#L49 ?

**Comment by Anton-Am** [comment]
Yeap.

Full composer config: https://github.com/Anton-Am/yii2-starter-kit/blob/master/composer.json

**Comment by samdark** [comment]
So where do you have assets now? Can you reproduce it using basic app template?

**Comment by Anton-Am** [comment]
Well..
I tested base & adv apps in native debian and i can't repeat the problem. I got assets problem only in vagrant version of project, but i don't understand where i'm fucked up.
```
Invalid Parameter - yii\base\InvalidParamException

The file or directory to be published does not exist: /var/www/vendor/yiisoft/yii2/authclient/assets
```

**Comment by samdark** [comment]
Where is actual location of assets in this case?

**Comment by Anton-Am** [comment]
Actual location of assets for yii2-authclient in /var/www/vendor/yiisoft/yii2-authclient/assets/

**Comment by samdark** [comment]
That's weird. Anyway, since there's no way to reproduce it, it can't be fixed.

**Pull request closed without merging**
