### PR TITLE
fix cancel redirect from linkedIn

### PR DESCRIPTION
**Pull request by msvit1989**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by samdark** [comment]
Have you verified it works well with other auth clients?

**Comment by msvit1989** [comment]
yes, i have verified, it works well with other soc auth clients

**Comment by samdark** [comment]
Then please add a line for changelog and I'll merge it.

**Comment by samdark** [comment]
Yes.

**Comment by msvit1989** [comment]
done

**Comment by samdark** [comment]
Merged. Thank you!

**Comment by jakim** [comment]
@samdark 
Can we now release version 2.1.6? Changes like this are very important.

**Comment by samdark** [comment]
Yes, I think so. Will make a release soon.

**Pull request merged**
