### PR TITLE
Add OpenID Connect client class for LinkedIn #381

### PR DESCRIPTION
**Pull request by mohammedNali**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | #381

### CODE REVIEW

**Comment by mohammedNali** [comment]
This PR introduces the LinkedIn OpenID Connect client class, ensuring compatibility with LinkedIn's latest authentication flow. Changes include updated scopes and attribute mappings, and handling ID tokens as per OpenID Connect standards.

**Comment by bizley** [comment]
Aren't we adding new clients no more?

**Comment by samdark** [comment]
Correct. @mohammedNali would you please release it as a separate package? Thanks.

**Comment by mohammedNali** [comment]
You mean a separate package just for Login with LinkedIn @samdark. I just wanted to contribute to this package :)

**Pull request closed without merging**
