### PR TITLE
Added auth client for LemonLDAP::NG

### PR DESCRIPTION
**Pull request by soisik**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | -

This PR add support for authenticating user using SSO [LemonLDAP::NG](https://lemonldap-ng.org)

### CODE REVIEW

**Comment by soisik** [comment]
Tests have failed due to php versions 5.4 and 5.5 not available on Xenial : https://travis-ci.community/t/php-5-4-and-5-5-archives-missing/3723/3

**Comment by samdark** [comment]
Thanks for contribution but it's better to release it as a separate extension. LemonLDAP::NG is not as common as clients included into official package.

**Comment by soisik** [comment]
Since LemonLDAP::NG uses standard OIDC, how about adding it as an OIDC generic client ?

Otherwise, we will develop a third party extension. I see there are a few referenced already.

**Comment by samdark** [comment]
Extension sounds like a good idea. Ping me when done, I'll reference it from docs.

**Pull request closed without merging**
