### PR TITLE
Fix #309 `BaseOAuth->beforeApiRequestSend()` try to refresh token if `BaseOAuth->autoRefreshAccessToken = true`

### LINKED ISSUE #309: beforeApiRequestSend logic improvement suggestion
### What steps will reproduce the problem?

When we have `BaseOAuth->autoRefreshAccessToken = true` and the access token is expired the `beforeApiRequestSend` method will trigger an  'Invalid access token.'

### What's expected?

I think if we have `autoRefreshAccessToken = true` and the access token is not valid anymore in fact we should not raised an exception but refresh the access token to have a valid one and be able to do the query, if refresh token is expired exception will be raised.

something like that should do the work:

```php
    public function beforeApiRequestSend($event)
    {
        $accessToken = $this->getAccessToken();
        if (!is_object($accessToken) || !$accessToken->getIsValid()) {
           if (!$this->autoRefreshAccessToken && is_object($accessToken)) {
             throw new Exception('Invalid access token.');
           }
          $this->refreshAccessToken($accessToken);
        }

        $this->applyAccessTokenToRequest($event->request, $accessToken);
    }
```

Does it seems a relevant change to you ?

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii Auth Client version | 2.2.7

### PR DESCRIPTION
**Pull request by marty-macfly**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #309

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Thanks!

**Comment by albertborsos** [comment]
FYI: this breaks my login. I think it sends an unnecessary refresh token request even if my access token is fresh.

Both Google and Facebook logins are broke. I will look after it soon.

**Comment by gustavovendramini** [comment]
After upgrade I'm getting

`yii\authclient\InvalidResponseException: Request failed with code: 400, message: {
  "error": "invalid_request",
  "error_description": "Missing required parameter: refresh_token"
} in /home/mypcards/mypcards/vendor/yiisoft/yii2-authclient/src/BaseOAuth.php:233`

**Comment by albertborsos** [comment]
Same at me. Revert back to 2.2.7 until fix is coming.

**Comment by samdark** [comment]
@gustavovendramini, @albertborsos I've merged the potential fix. Please try dev-master@dev.

**Comment by gustavovendramini** [comment]
@samdark Login worked! I tested it on Google and Facebook.

**Comment by samdark** [comment]
OK. Going to tag a release.

**Pull request merged**
