### PR TITLE
Google OAuth client permission fix

### PR DESCRIPTION
**Pull request by karakum**

### CODE REVIEW

**Comment by samdark** [comment]
Are you sure it's correct?

**Comment by karakum** [comment]
Here https://developers.google.com/identity/protocols/googlescopes list of all google services scopes.
And here https://developers.google.com/identity/protocols/googlescopes#oauth2v2 scopes for using "Google OAuth2 API, v2".

**Comment by samdark** [comment]
Have you tested it?

**Comment by karakum** [comment]
Yes

**Comment by klimov-paul** [comment]
I can't the any problem: current scopes are supported as 'Sign In' API:
https://developers.google.com/identity/protocols/googlescopes#google_sign-in

Why should we change them?

**Comment by karakum** [comment]
I checked in the new application and can agree with you, it is works good. 
It is so strange, but some time ago I had problems with it in other application. And then I found decision by changing scopes with 'https://www.googleapis.com/auth/userinfo.' prefix.
Thread can be closed.

**Pull request closed without merging**
