### PR TITLE
Use nonce from the authentication request

### LINKED ISSUE #332: OIDC: Nonce is missing in the authentication request
Currently, the nonce is generated when the access token request is done:

https://github.com/yiisoft/yii2-authclient/blob/e9e4ce479b7c9ea4f6a90ce015e362515f4723a6/src/OpenIdConnect.php#L250-L257

However the [OpenID Connect specification](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) states that, if used, the nonce should be passed from the authentication request.

> nonce    OPTIONAL. String value used to associate a Client session with an ID Token, and to mitigate replay attacks. **The value is passed through unmodified from the Authentication Request to the ID Token.** [...]

Without this, this plugin is unusable with some providers like [canaille](https://gitlab.com/yaal/canaille).

### PR DESCRIPTION
**Pull request by azmeuk**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | Fixes #332

### CODE REVIEW

**Review by samdark — APPROVED** [review]
Looks alright. Is it possible to cover it with tests and add a line to CHANGELOG?

**Comment by azmeuk** [comment]
I can try to write tests, but `make test` shows me this error:

```
 env LANG=C make test
test -d tests/docker || git clone https://github.com/cebe/jenkins-test-docker tests/docker
cd tests/docker && git checkout -- . && git pull
Already up to date.
mkdir -p tests/dockerids
cd tests/docker/php && sh build.sh
building base docker image for php.
Sending build context to Docker daemon  6.144kB
Step 1/10 : FROM debian:wheezy
 ---> 10fcec6d95c4
Step 2/10 : RUN   DEBIAN_FRONTEND=noninteractive apt-get update &&   DEBIAN_FRONTEND=noninteractive apt-get upgrade -y &&   DEBIAN_FRONTEND=noninteractive apt-get install -y git curl vim build-essential pkg-config autoconf bison re2c libxml2-dev
 ---> Running in 8a3ec2ddf3ca
Ign http://security.debian.org wheezy/updates Release.gpg
Ign http://security.debian.org wheezy/updates Release
Err http://security.debian.org wheezy/updates/main amd64 Packages

Ign http://deb.debian.org wheezy Release.gpg
Err http://security.debian.org wheezy/updates/main amd64 Packages

Err http://security.debian.org wheezy/updates/main amd64 Packages

Ign http://deb.debian.org wheezy-updates Release.gpg
Err http://security.debian.org wheezy/updates/main amd64 Packages

Err http://security.debian.org wheezy/updates/main amd64 Packages
  404  Not Found [IP: 151.101.194.132 80]
Ign http://deb.debian.org wheezy Release
Ign http://deb.debian.org wheezy-updates Release
Err http://deb.debian.org wheezy/main amd64 Packages
  404  Not Found
Err http://deb.debian.org wheezy-updates/main amd64 Packages
  404  Not Found
W: Failed to fetch http://security.debian.org/debian-security/dists/wheezy/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.194.132 80]

W: Failed to fetch http://deb.debian.org/debian/dists/wheezy/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://deb.debian.org/debian/dists/wheezy-updates/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c DEBIAN_FRONTEND=noninteractive apt-get update &&   DEBIAN_FRONTEND=noninteractive apt-get upgrade -y &&   DEBIAN_FRONTEND=noninteractive apt-get install -y git curl vim build-essential pkg-config autoconf bison re2c libxml2-dev' returned a non-zero code: 100
building docker for php php-5.6.8.
Sending build context to Docker daemon  12.29kB
Step 1/8 : FROM yiitest/php-base:latest
pull access denied for yiitest/php-base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
make: *** [Makefile:20: docker-php] Error 1
```

**Comment by samdark** [comment]
Just ignore makefile and use `./vendor/bin/phpunit` insteead.

**Comment by azmeuk** [comment]
I added a test that checks the nonce is correctly passed and retrieved in the auth request. However I did not know how to check that the nonce is passed again in the token request without changing the functional code.

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
