### PR TITLE
Allow params to be array or string.  Allow curl Files.  Solves several issues. 

### PR DESCRIPTION
**Pull request by smorocho**
Source: (http://php.net/manual/en/function.curl-setopt.php)

Whereas CURLOPT_POSTFIELDS 'can either be passed as a urlencoded string [...] or as an array with the field name as key and field data as value' 
Whereas 'Passing an array to CURLOPT_POSTFIELDS will encode the data as multipart/form-data, while passing a URL-encoded string will encode the data as application/x-www-form-urlencoded' 

I propose changes to yii2-authclient to allow for $params to be either an array or string.
Setting Content-Type explicitly is not required in composeRequestCurlOptions().
Also, determining when to use http_build_query depends on if array has any CURLFiles or not.
LinkedIn.php is changed to pass authToken in headers to allow for JSON api requests such as

	// get session session with user access token
	$token = new OAuthToken([
		'token' => 'ACCESS_TOKEN',
	]);
	$linkedin = new LinkedIn([
		'accessToken' => $token,
		'clientId' => 'CLIENT_ID',
		'clientSecret' => 'CLIENT_SECRET'
	]);
                         
	$data = [
		'comment' => 'Hello World',
		'visibility'=> ['code'=>'anyone']
	];
	try {
		$linkedin_response = $linkedin->api('people/~/shares?format=json', 'POST', json_encode($data), ['Content-Type: application/json']);
		$linkedin_updateKey = $linkedin_response['updateKey'];
	} catch(\Exception $ex) {
		error_log("Linkedin error posting message: " . var_export($ex->getMessage(), true));
	}

### CODE REVIEW

**Comment by smorocho** [comment]
@klimov-paul I'm not sure what the label BC breaking means.  Passing array as $params (which was the only thing you could do in the past) should still work exactly the same.  Could you please elaborate?

**Comment by klimov-paul** [comment]
The signature of the methods has been changed, thus if anyone extends class and overriddes those methods he will receive E_STRICT error.

**Comment by smorocho** [comment]
@klimov-paul   I see. What are the next steps in the pull request process.  Thanks.

**Comment by klimov-paul** [comment]
BC breaking changes usually allowed only for the major release, e.g. 2.1.
I will keep this open until corresponding milestone.

**Comment by klimov-paul** [comment]
Resolved via #117

**Pull request closed without merging**
