### PR TITLE
Update quick-start.md

### PR DESCRIPTION
**Pull request by SOHELAHMED7**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | -

Enhance docs

### CODE REVIEW

**Comment by samdark** [comment]
Why is status needed?

**Comment by SOHELAHMED7** [comment]
I am using this package with yii2-app-basic. 

I have applied migrations similar to that in [docs](https://github.com/yiisoft/yii2-authclient/blob/master/docs/guide/installation.md#storing-authorization-data) and yii2-app-advanced 

They both have status column

User model have status too in yii2-app-basic and in advanced template. User with only status=active can log in.

Most of the real world Yii2 project are based on this templates

The response we get from OAuth server such as GitHub, GitLab etc have verified email. Though some don't even send email in the response. But in most case we have detail that is verified 

I successfully integrated this package to the project I am working on. I was successfully able to communicate with GitHub (etc). When GitHub redirect back to our app (callback/redirect URL) I was not automatically logged in.There was no error. I spent significant time to solve this issue. This was tough to debug. At the end I found that due to status != active, the login was not working

As this does not change any package code, my proposed change is in the docs not in the code so I think this is nice to have addition.

Possible someone else will save some time if there is `status` present in the docs.

**Comment by bizley** [comment]
I guess it wouldn't hurt.

**Comment by SOHELAHMED7** [comment]
I think then at least keeping a note similar to  

```php
$user = new User([
            'username' => $username,
            'email' => $email,
            'password' => $password,
            // 'status' => User::STATUS_ACTIVE //  ensure you set status properly
        ]);
```

would be better

**Comment by samdark** [comment]
Agree. Commented-out variant looks good.

**Comment by samdark** [comment]
Thanks.

**Pull request merged**
