### PR TITLE
Added new Spotify client

### PR DESCRIPTION
**Pull request by freezy-sk**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | -

### CODE REVIEW

**Comment by samdark** [comment]
Won't add more clients. Please release it as an extension.

**Comment by freezy-sk** [comment]
@samdark why should I make extension for few lines of code when it can be here?
OAuth bundle for Symfony https://github.com/hwi/HWIOAuthBundle has 40 clients

**Comment by klimov-paul** [comment]
> why should I make extension for few lines of code when it can be here?

Maintaining your own repository means you are taking the whole responsibility for it and handle possible issues.
Our resources are stretched enough as it is - we can not afford additional functionality for maintainance.

> OAuth bundle for Symfony https://github.com/hwi/HWIOAuthBundle has 40 clients

That is because it is official, and Symfony core team do not handle it.
If you are concern about growing numbers of the extension based on `yii2-authclient` - you should arrange a separated communitity and setup a solid project, which will consume all clients, which are not represented at `yii2-authclient`. So it can look like your example from Symfony.

**Comment by freezy-sk** [comment]
@klimov-paul I got your point, but in this case there is a little difference between Symfony and Yii.
Symfony core does not provide OAuth handling and whole functionality is maintained by team making HWIOAuthBundle. The same community can be around `yii2-authclient` instead of making new packages and communities.

**Pull request closed without merging**
