### PR TITLE
Add apiVersion for VKontakte client

### PR DESCRIPTION
**Pull request by isudakoff**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes

See:
https://vk.com/dev/version_update
https://vk.com/dev/api_requests

### CODE REVIEW

**Comment by isudakoff** [comment]
@cebe Can I update it myself?

**Comment by cebe** [comment]
@isudakoff sure, you can edit the CHANGELOG file and push the changes to the branch of this PR. you have used master, its better to create a new branch next time. See also https://github.com/yiisoft/yii2/blob/master/docs/internals/git-workflow.md

**Comment by isudakoff** [comment]
@cebe It's done!

**Comment by samdark** [comment]
Merged. Thank you!

**Comment by FractalizeR** [comment]
Can you release this as a new release so that we could add this dependency to the composer? Need this feature ;)

**Comment by dmirogin** [comment]
@FractalizeR you can set master-branch for composer extension.

**Comment by FractalizeR** [comment]
This product I'm working on goes to production in a week. I can't depend on unstable master. It would be great to set a version constraint because my deployment scripts call composer and I deploy often.

**Comment by klimov-paul** [comment]
No release will be available until core `yii2` version 2.0.13 release, since it is bocking for PHP 7.2 support.

**Comment by FractalizeR** [comment]
Then it's not until half a year passes away ;)
BTW, I don't see any PHP7 specifics in any code commited after 2.1.3.

**Comment by klimov-paul** [comment]
See:
https://github.com/yiisoft/yii2/issues/7936
https://github.com/yiisoft/yii2/pull/14478

And:
https://github.com/yiisoft/yii2-authclient/blob/master/OAuthToken.php#L27

**Comment by FractalizeR** [comment]
Yeah, I see, thanks. But I still don't see why not to release 2.1.4 with this commit included as it's important for working witk VK profile. Of course, this is still for the author to decide.

As for Yii 2.0.13 - it's already two months due with only about 50% of issues solved and I stopped waiting. It's quite sad also to see qiangxue [stepping away](https://github.com/yiisoft/yii2/graphs/contributors) from Yii development.

Thank you anyway for your great product. It saved me many hours coding. Keep up, guys!

**Comment by cebe** [comment]
> As for Yii 2.0.13 - it's already two months due with only about 50% of issues solved and I stopped waiting. It's quite sad also to see qiangxue stepping away from Yii development.

development is not stalled because of Qiang missing, but rather because we are working on the new website right now :) If that is finished, framework development will get more attention again.

**Comment by FractalizeR** [comment]
I see. Well, let's wait ;) And good luck!

**Pull request merged**
