### PR TITLE
Fix github https://developer.github.com/changes/2019-11-05-deprecated…

### PR DESCRIPTION
**Pull request by raidkon**
…-passwords-and-authorizations-api/#authenticating-using-query-parameters

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | what?)
| Tests pass?   | yes
| Fixed issues  | #292

### CODE REVIEW

**Comment by raidkon** [comment]
@samdark Please merge PR

**Comment by samdark** [comment]
@switchy would you please test it on your setup?

@raidkon thanks! Would you please add a line for changelog?

**Comment by raidkon** [comment]
@samdark done

**Comment by samdark** [comment]
Merged. Thank you for the fix, @raidkon.

**Pull request merged**
