### PR TITLE
Add ability to use requestToken to compose signature key for Oauth1

### PR DESCRIPTION
**Pull request by Alien-Le**

### CODE REVIEW

**Comment by umanamente** [comment]
Related to issue #41

**Comment by umanamente** [comment]
@Alien-Le, so could you please apply changes and test it?

**Comment by umanamente** [comment]
Also need 
```php
$this->removeState('requestToken');
```
at the beginning of `fetchRequestToken`:
```php
    public function fetchRequestToken(array $params = [])
    {
        $this->removeState('token');
        $this->removeState('requestToken');
        ...
```

**Comment by Alien-Le** [comment]
Why do we need it there?

**Comment by umanamente** [comment]
Because if `requestToken` is present somehow, it will be included in the signature while obtaining new temporary key, which is not correct and leads to "invalid signature" error.

**Comment by umanamente** [comment]
Works fine with Twitter and Wikipedia clients.

**Pull request closed without merging**
